In [7]:
from sklearn.datasets import load_iris

In [9]:
iris_data = load_iris() #it return a bunch onject which is very similar to python dictionary(key value pain)

In [10]:
print("Keys of iris dataset \n {}".format(iris_dataset.keys()))

Keys of iris dataset 
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [11]:
print("Target name \n {}".format(iris_dataset['target_names']))

Target name 
 ['setosa' 'versicolor' 'virginica']


In [12]:
print("Feature name \n {}".format(iris_dataset['feature_names']))

Feature name 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
print("Shape of data \n {}".format(iris_dataset['data'].shape))#data contains 150 samples along with 4 features

Shape of data 
 (150, 4)


In [14]:
print("The first 5 datas \n {}".format(iris_dataset['data'][:5]))

The first 5 datas 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [15]:
print("labels for the above 5 datas \n {}".format(iris_dataset['target'][:5]))

labels for the above 5 datas 
 [0 0 0 0 0]


In [17]:
#0 means setosa, 1 means versicolor, and 2 means virginica

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X = iris_data.data

In [20]:
y = iris_data.target

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [22]:
print("Training data shape \n {}".format(X_train.shape))

Training data shape 
 (112, 4)


In [23]:
print("Testing data shape \n {}".format(X_test.shape))

Testing data shape 
 (38, 4)


In [24]:
#The best thing to use train_test_split function is before it split the data first it shuffle the whole dataset
#using psudarandom number generator

In [25]:
import mglearn

In [44]:
import numpy as np

In [45]:
import pandas as pd

In [46]:
import matplotlib.pyplot as plt

In [47]:
iris_dataframe = pd.DataFrame(X_train, columns= iris_data.feature_names)

In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
knn = KNeighborsClassifier(n_neighbors = 1)

In [50]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [51]:
X_new = np.array([[5, 2.9, 1, 0.2]])

In [52]:
print("The shape of X_new \n {}".format(X_new.shape))

The shape of X_new 
 (1, 4)


In [53]:
prediction = knn.predict(X_new)

In [54]:
print("prediction {}".format(prediction))

prediction [0]


In [60]:
print("prediction of target name is {}".format(iris_data['target_names'][prediction]))

prediction of target name is ['setosa']


In [61]:
y_pred = knn.predict(X_test)

In [62]:
print("Test prediction \n {}".format(y_pred))

Test prediction 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [65]:
print("Test set score \n {:.2f}".format(np.mean(y_pred == y_test)))

Test set score 
 0.97


In [66]:
print("Test set score using knn object score method \n {:.2f}".format(knn.score(X_test, y_test)))

Test set score using knn object score method 
 0.97
